config/routes.rb
Rails.application.routes.draw do
  resources :lists
  get 'site/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @list = List.new
    @lists = List.all
    # render 'lists/index.html.erb'
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    @list.name = params[:list][:name]
    @list.save
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoMvcLv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Your List</h1>
    <input class="new-todo" placeholder="Make new lists" autofocus="">
  </header>

  <section class="main">
    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %></label>
        </div>
      </li>
        <% end %>
    </ul>
  </section>

  <footer class="footer">
  </footer>
</section>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <input class="new-todo" placeholder="Add an item ..." autofocus="">
  </header>

  <section class="main">
    <input class="toggle-all" type="checkbox">
    <label for="toggle-all">Mark all as complete</label>
    <ul class="todo-list">
      <li>
        <div class="view">
          <label>Milk</label>
        </div>
      </li>
      <li>
        <div class="view">
          <label>Cookies</label>
        </div>
      </li>
    </ul>
  </section>

  <footer class="footer">
  </footer>
</section>